version: '3.8'

services:
  go:
    container_name: ${PROJECT_NAME-go-debugger}-go
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER-1000}'
    volumes:
      - "./src:/app"
    tty: true
    user: "${WWWUSER-1000}:${WWWUSER-1000}"
